x-common: &common
  environment: &common-env
    FLASK_DEBUG: 1
    FLASK_APP: "main.py"
    IN_DOCKER_CONTAINER: 1
  build: &common-build-context
    context: .
  healthcheck: &common-healthcheck-timing
    interval: 30s
    timeout: 10s
    retries: 5

x-app-vol: &app-vol "./:/application"

services:
  api:
    <<: *common
    build:
      <<: *common-build-context
      dockerfile: Dockerfile
    container_name: logistica_backend_${TARGET}
    networks:
      - local_net
    volumes:
      - *app-vol
    ports:
      - "${API_PORT}:${API_PORT}"
    healthcheck:
      <<: *common-healthcheck-timing
      test: ["CMD", "curl", "--fail", "http://localhost:${API_PORT}/"]
    platform: linux/amd64
    restart: always

networks:
  local_net:
    driver: bridge
