services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: logistica_backend
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    networks:
      - logistica_net
    volumes:
      - ./backend:/application
    ports:
      - 6002:6002
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:6002/"]
      interval: 30s
      timeout: 10s
      retries: 5
    platform: linux/amd64
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: logistica_frontend
    networks:
      - logistica_net
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 8002:80
      - 4002:443
    restart: always

networks:
  logistica_net:
    driver: bridge
